import pw from 'file:///C:/Users/mahin/.claude/skills/playwright-skill/node_modules/playwright/index.js';
const {chromium}=pw;const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:1000}});
await p.goto('file:///D:/cursor/netim-seo-os/klienci/kobi-meble/index.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(900);
await p.evaluate(()=>{const n=[...document.querySelectorAll('.navitem')].find(x=>x.textContent.trim().startsWith('Meble'));if(n)n.click();});
await p.waitForTimeout(300);
await p.evaluate(()=>{const c=[...document.querySelectorAll('.mcat')].find(x=>x.textContent.includes('Komody'));if(c)c.click();});
await p.waitForTimeout(400);
const chips=await p.evaluate(()=>[...document.querySelectorAll('.chip')].map(c=>c.textContent.replace(/\s+/g,' ').trim()).slice(0,8));
console.log('Chipy Komody:',JSON.stringify(chips));
await p.screenshot({path:'playwright-tmp/site-kw.png'});
await b.close();
